name: 'ðŸ”„ Sync Label Config'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 1 * *'

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          config-file: https://raw.githubusercontent.com/k3rnels-actions/.github/main/.github/labels.yaml
          delete-other-labels: true
          token: ${{ secrets.GITHUB_TOKEN }}
